# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'LinWearKit_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LinWearKit_Demo

  pod 'LinWearKit', git: 'https://github.com/wsr1949/LinWearKit.git' #SDK

  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'Realm'
  pod 'BRPickerView'

end
